services:
  nginx-modsecurity:
    build: .
    container_name: nginx-modsecurity
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./modsecurity/modsecurity.conf:/etc/nginx/modsecurity/modsecurity.conf
      - ./modsecurity/crs-setup.conf:/etc/nginx/modsecurity/crs-setup.conf
      - ./modsecurity/rules:/etc/nginx/modsecurity/rules
    environment:
      - VIRTUAL_HOST=switch1.zentec.network
