services:
  nginx-modsecurity:
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      VIRTUAL_HOST: "switch1.zentec.network"
      EXTERNAL_IP: "10.0.0.2"
    volumes:
      - ./template-variables:/etc/nginx/templates/10-variables.conf.template:ro
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./modsecurity/modsecurity.conf:/etc/nginx/modsecurity/modsecurity.conf:ro
      - ./modsecurity/crs-setup.conf:/etc/nginx/modsecurity/crs-setup.conf:ro
      - ./modsecurity/rules:/etc/nginx/modsecurity/rules:ro
      - ./certs:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
